Fix parsing invalid href
oscarotero/Embed pull request #502
Opened 2022-10-09 17:02 UTC by grandeljay

This is my attempt to fix #501

> In this case, I'd create a helper, so it can be used in other places. Something like:

@oscarotero I wasn't sure what exactly you mean, but maybe something like this?

2022-10-09 17:24 UTC, oscarotero requested changes

2022-10-09 17:24 UTC, oscarotero commented on src/Detectors/Languages.php
> +    private function isEmpty($value): boolval
This function should be here https://github.com/oscarotero/Embed/blob/master/src/functions.php

The return type `boolval` doesn't exist. It should be `bool`.

2022-10-09 17:24 UTC, oscarotero commented on src/Detectors/Languages.php
> +            if (isEmpty()) {
This function hasn't any argument

2022-10-09 17:49 UTC, grandeljay commented
Sorry you had to see that. This time I tested my changes.

I'm also wondering if it would make sense to use the splat operator so we could use 
```php
if (self::isEmpty($language, $href)) {
```
instead?

```php
private function isEmpty(string ...$values): bool
{
    $skipValues = array(
        'undefined',
    );

    foreach ($values as $value) {
        if (empty($value) || in_array($value, $skipValues)) {
            return true;
        }
    }

    return false;
}
```

2022-10-09 18:40 UTC, oscarotero commented
> I'm also wondering if it would make sense to use the splat operator

Ok, but the arguments can be of any type, not only `string` (it must return `true` for `null`, `0`, `[]`, etc).

The `isEmpty` function shouldn't be a private method but a function that can be imported by other classes. The global helpers are located in this file: https://github.com/oscarotero/Embed/blob/master/src/functions.php

2022-10-10 06:42 UTC, grandeljay commented
> Ok, but the arguments can be of any type, not only string (it must return true for null, 0, [], etc).

`getAttribute()` seems to return a nullable string. If this helper is just used for this method, I think requiring a `string` parameter makes sense.

If you want to make the helper more "future proof" by allowing all types, I don't think we can continue to use `empty()` since it
> Returns true if var does not exist or has a value that is empty or equal to zero, aka falsey, [...]. Otherwise returns false.

So `null` and `0` would be considered empty values which you do not seem to want. 

> The isEmpty function shouldn't be a private method but a function that can be imported by other classes. The global helpers are located in this file: https://github.com/oscarotero/Embed/blob/master/src/functions.php

Thanks! I'll change it!

2022-10-10 10:45 UTC, merged

2022-10-10 10:46 UTC, oscarotero commented
Looks good to me. Thanks!